/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiElectricRouteImport } from './routes/api/electric'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as protectedAdminRouteRouteImport } from './routes/(protected)/admin/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as protectedDashboardTagsRouteImport } from './routes/(protected)/dashboard/tags'
import { Route as protectedDashboardSettingsRouteImport } from './routes/(protected)/dashboard/settings'
import { Route as protectedDashboardProfileRouteImport } from './routes/(protected)/dashboard/profile'
import { Route as protectedDashboardDietsRouteImport } from './routes/(protected)/dashboard/diets'
import { Route as protectedDashboardCuisinesRouteImport } from './routes/(protected)/dashboard/cuisines'
import { Route as protectedDashboardCategoriesRouteImport } from './routes/(protected)/dashboard/categories'
import { Route as protectedDashboardRecipesIndexRouteImport } from './routes/(protected)/dashboard/recipes/index'
import { Route as protectedDashboardRecipesSharedRouteRouteImport } from './routes/(protected)/dashboard/recipes/shared/route'
import { Route as protectedDashboardRecipesFavoritesRouteRouteImport } from './routes/(protected)/dashboard/recipes/favorites/route'
import { Route as protectedDashboardRecipesAddRouteRouteImport } from './routes/(protected)/dashboard/recipes/add/route'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricRoute = ApiElectricRouteImport.update({
  id: '/api/electric',
  path: '/api/electric',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminRouteRoute = protectedAdminRouteRouteImport.update({
  id: '/(protected)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardTagsRoute = protectedDashboardTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => protectedDashboardRouteRoute,
} as any)
const protectedDashboardSettingsRoute =
  protectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardProfileRoute =
  protectedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardDietsRoute = protectedDashboardDietsRouteImport.update({
  id: '/diets',
  path: '/diets',
  getParentRoute: () => protectedDashboardRouteRoute,
} as any)
const protectedDashboardCuisinesRoute =
  protectedDashboardCuisinesRouteImport.update({
    id: '/cuisines',
    path: '/cuisines',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardCategoriesRoute =
  protectedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardRecipesIndexRoute =
  protectedDashboardRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardRecipesSharedRouteRoute =
  protectedDashboardRecipesSharedRouteRouteImport.update({
    id: '/recipes/shared',
    path: '/recipes/shared',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardRecipesFavoritesRouteRoute =
  protectedDashboardRecipesFavoritesRouteRouteImport.update({
    id: '/recipes/favorites',
    path: '/recipes/favorites',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)
const protectedDashboardRecipesAddRouteRoute =
  protectedDashboardRecipesAddRouteRouteImport.update({
    id: '/recipes/add',
    path: '/recipes/add',
    getParentRoute: () => protectedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof protectedAdminRouteRoute
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api/electric': typeof ApiElectricRoute
  '/dashboard/categories': typeof protectedDashboardCategoriesRoute
  '/dashboard/cuisines': typeof protectedDashboardCuisinesRoute
  '/dashboard/diets': typeof protectedDashboardDietsRoute
  '/dashboard/profile': typeof protectedDashboardProfileRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRoute
  '/dashboard/tags': typeof protectedDashboardTagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/recipes/add': typeof protectedDashboardRecipesAddRouteRoute
  '/dashboard/recipes/favorites': typeof protectedDashboardRecipesFavoritesRouteRoute
  '/dashboard/recipes/shared': typeof protectedDashboardRecipesSharedRouteRoute
  '/dashboard/recipes': typeof protectedDashboardRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof protectedAdminRouteRoute
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api/electric': typeof ApiElectricRoute
  '/dashboard/categories': typeof protectedDashboardCategoriesRoute
  '/dashboard/cuisines': typeof protectedDashboardCuisinesRoute
  '/dashboard/diets': typeof protectedDashboardDietsRoute
  '/dashboard/profile': typeof protectedDashboardProfileRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRoute
  '/dashboard/tags': typeof protectedDashboardTagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/recipes/add': typeof protectedDashboardRecipesAddRouteRoute
  '/dashboard/recipes/favorites': typeof protectedDashboardRecipesFavoritesRouteRoute
  '/dashboard/recipes/shared': typeof protectedDashboardRecipesSharedRouteRoute
  '/dashboard/recipes': typeof protectedDashboardRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)/admin': typeof protectedAdminRouteRoute
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/api/electric': typeof ApiElectricRoute
  '/(protected)/dashboard/categories': typeof protectedDashboardCategoriesRoute
  '/(protected)/dashboard/cuisines': typeof protectedDashboardCuisinesRoute
  '/(protected)/dashboard/diets': typeof protectedDashboardDietsRoute
  '/(protected)/dashboard/profile': typeof protectedDashboardProfileRoute
  '/(protected)/dashboard/settings': typeof protectedDashboardSettingsRoute
  '/(protected)/dashboard/tags': typeof protectedDashboardTagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(protected)/dashboard/recipes/add': typeof protectedDashboardRecipesAddRouteRoute
  '/(protected)/dashboard/recipes/favorites': typeof protectedDashboardRecipesFavoritesRouteRoute
  '/(protected)/dashboard/recipes/shared': typeof protectedDashboardRecipesSharedRouteRoute
  '/(protected)/dashboard/recipes/': typeof protectedDashboardRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/api/electric'
    | '/dashboard/categories'
    | '/dashboard/cuisines'
    | '/dashboard/diets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/tags'
    | '/api/auth/$'
    | '/dashboard/recipes/add'
    | '/dashboard/recipes/favorites'
    | '/dashboard/recipes/shared'
    | '/dashboard/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/api/electric'
    | '/dashboard/categories'
    | '/dashboard/cuisines'
    | '/dashboard/diets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/tags'
    | '/api/auth/$'
    | '/dashboard/recipes/add'
    | '/dashboard/recipes/favorites'
    | '/dashboard/recipes/shared'
    | '/dashboard/recipes'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)/admin'
    | '/(protected)/dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/api/electric'
    | '/(protected)/dashboard/categories'
    | '/(protected)/dashboard/cuisines'
    | '/(protected)/dashboard/diets'
    | '/(protected)/dashboard/profile'
    | '/(protected)/dashboard/settings'
    | '/(protected)/dashboard/tags'
    | '/api/auth/$'
    | '/(protected)/dashboard/recipes/add'
    | '/(protected)/dashboard/recipes/favorites'
    | '/(protected)/dashboard/recipes/shared'
    | '/(protected)/dashboard/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedAdminRouteRoute: typeof protectedAdminRouteRoute
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  ApiElectricRoute: typeof ApiElectricRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric': {
      id: '/api/electric'
      path: '/api/electric'
      fullPath: '/api/electric'
      preLoaderRoute: typeof ApiElectricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/tags': {
      id: '/(protected)/dashboard/tags'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof protectedDashboardTagsRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/settings': {
      id: '/(protected)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/profile': {
      id: '/(protected)/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof protectedDashboardProfileRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/diets': {
      id: '/(protected)/dashboard/diets'
      path: '/diets'
      fullPath: '/dashboard/diets'
      preLoaderRoute: typeof protectedDashboardDietsRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/cuisines': {
      id: '/(protected)/dashboard/cuisines'
      path: '/cuisines'
      fullPath: '/dashboard/cuisines'
      preLoaderRoute: typeof protectedDashboardCuisinesRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/categories': {
      id: '/(protected)/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof protectedDashboardCategoriesRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/recipes/': {
      id: '/(protected)/dashboard/recipes/'
      path: '/recipes'
      fullPath: '/dashboard/recipes'
      preLoaderRoute: typeof protectedDashboardRecipesIndexRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/recipes/shared': {
      id: '/(protected)/dashboard/recipes/shared'
      path: '/recipes/shared'
      fullPath: '/dashboard/recipes/shared'
      preLoaderRoute: typeof protectedDashboardRecipesSharedRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/recipes/favorites': {
      id: '/(protected)/dashboard/recipes/favorites'
      path: '/recipes/favorites'
      fullPath: '/dashboard/recipes/favorites'
      preLoaderRoute: typeof protectedDashboardRecipesFavoritesRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
    '/(protected)/dashboard/recipes/add': {
      id: '/(protected)/dashboard/recipes/add'
      path: '/recipes/add'
      fullPath: '/dashboard/recipes/add'
      preLoaderRoute: typeof protectedDashboardRecipesAddRouteRouteImport
      parentRoute: typeof protectedDashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedDashboardRouteRouteChildren {
  protectedDashboardCategoriesRoute: typeof protectedDashboardCategoriesRoute
  protectedDashboardCuisinesRoute: typeof protectedDashboardCuisinesRoute
  protectedDashboardDietsRoute: typeof protectedDashboardDietsRoute
  protectedDashboardProfileRoute: typeof protectedDashboardProfileRoute
  protectedDashboardSettingsRoute: typeof protectedDashboardSettingsRoute
  protectedDashboardTagsRoute: typeof protectedDashboardTagsRoute
  protectedDashboardRecipesAddRouteRoute: typeof protectedDashboardRecipesAddRouteRoute
  protectedDashboardRecipesFavoritesRouteRoute: typeof protectedDashboardRecipesFavoritesRouteRoute
  protectedDashboardRecipesSharedRouteRoute: typeof protectedDashboardRecipesSharedRouteRoute
  protectedDashboardRecipesIndexRoute: typeof protectedDashboardRecipesIndexRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardCategoriesRoute: protectedDashboardCategoriesRoute,
    protectedDashboardCuisinesRoute: protectedDashboardCuisinesRoute,
    protectedDashboardDietsRoute: protectedDashboardDietsRoute,
    protectedDashboardProfileRoute: protectedDashboardProfileRoute,
    protectedDashboardSettingsRoute: protectedDashboardSettingsRoute,
    protectedDashboardTagsRoute: protectedDashboardTagsRoute,
    protectedDashboardRecipesAddRouteRoute:
      protectedDashboardRecipesAddRouteRoute,
    protectedDashboardRecipesFavoritesRouteRoute:
      protectedDashboardRecipesFavoritesRouteRoute,
    protectedDashboardRecipesSharedRouteRoute:
      protectedDashboardRecipesSharedRouteRoute,
    protectedDashboardRecipesIndexRoute: protectedDashboardRecipesIndexRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedAdminRouteRoute: protectedAdminRouteRoute,
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  ApiElectricRoute: ApiElectricRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
